require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Car = require('../models/Car');

const additionalCars = [
    {
        make: 'Maruti Suzuki',
        model: 'Swift',
        variant: 'VXi',
        year: 2018,
        price: 520000,
        mileage: 45000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'Fire Red',
        intColor: 'Black',
        ownership: '1st Owner',
        rtoLocation: 'MH-14 (Pimpri-Chinchwad)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: false, touchscreen: true, reverseCamera: false },
        description: 'Well maintained Swift VXi. Single owner, smooth engine.',
        images: [{ url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80', public_id: 'autovault-cars/swift-2018' }]
    },
    {
        make: 'Hyundai',
        model: 'i20',
        variant: 'Sportz',
        year: 2015,
        price: 480000,
        mileage: 60000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'Polar White',
        intColor: 'Beige & Black',
        ownership: '2nd Owner',
        rtoLocation: 'DL-8C (Delhi)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: true },
        description: 'Excellent condition i20 with regular service history.',
        images: [{ url: 'https://images.unsplash.com/photo-1616422285623-14ffea3166d4?w=1200&q=80', public_id: 'autovault-cars/i20-2015' }]
    },
    {
        make: 'Honda',
        model: 'City',
        variant: 'V MT',
        year: 2012,
        price: 400000,
        mileage: 85000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Sedan',
        extColor: 'Alabaster Silver',
        intColor: 'Beige',
        ownership: '1st Owner',
        rtoLocation: 'KA-51 (Bengaluru)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: false },
        description: 'Classic Honda City with reliable i-VTEC engine.',
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80', public_id: 'autovault-cars/city-2012' }]
    },
    {
        make: 'Tata',
        model: 'Nexon',
        variant: 'XZ+',
        year: 2019,
        price: 850000,
        mileage: 38000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Foliage Green',
        intColor: 'Grey',
        ownership: '1st Owner',
        rtoLocation: 'TS-07 (Hyderabad)',
        isFeatured: true,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Safety-rated 5-star SUV. Powerful diesel engine.',
        images: [{ url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&q=80', public_id: 'autovault-cars/nexon-2019' }]
    },
    {
        make: 'Mahindra',
        model: 'XUV500',
        variant: 'W8',
        year: 2014,
        price: 650000,
        mileage: 95000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 7,
        bodyType: 'SUV',
        extColor: 'Volcano Black',
        intColor: 'Premium Black',
        ownership: '2nd Owner',
        rtoLocation: 'TN-22 (Chennai)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Spacious 7-seater SUV, fully loaded W8 variant.',
        images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80', public_id: 'autovault-cars/xuv500-2014' }]
    },
    {
        make: 'Hyundai',
        model: 'Creta',
        variant: 'SX',
        year: 2017,
        price: 950000,
        mileage: 55000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Phantom Black',
        intColor: 'Black & Beige',
        ownership: '1st Owner',
        rtoLocation: 'MH-04 (Thane)',
        isFeatured: true,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Popular compact SUV with a punchy CRDi engine.',
        images: [{ url: 'https://images.unsplash.com/photo-1620882775199-73fb6eb6fec2?w=1200&q=80', public_id: 'autovault-cars/creta-2017' }]
    },
    {
        make: 'Maruti Suzuki',
        model: 'Dzire',
        variant: 'ZXi',
        year: 2013,
        price: 420000,
        mileage: 70000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Sedan',
        extColor: 'Silky Silver',
        intColor: 'Beige',
        ownership: '3rd Owner',
        rtoLocation: 'UP-16 (Noida)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: false },
        description: 'Economical and low maintenance family sedan.',
        images: [{ url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80', public_id: 'autovault-cars/dzire-2013' }]
    },
    {
        make: 'Ford',
        model: 'EcoSport',
        variant: 'Titanium',
        year: 2016,
        price: 600000,
        mileage: 62000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Diamond White',
        intColor: 'Dark Grey',
        ownership: '1st Owner',
        rtoLocation: 'KL-01 (Thiruvananthapuram)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: true },
        description: 'Solid build quality with excellent handling and ground clearance.',
        images: [{ url: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=1200&q=80', public_id: 'autovault-cars/ecosport-2016' }]
    },
    {
        make: 'Volkswagen',
        model: 'Polo',
        variant: 'Highline',
        year: 2011,
        price: 280000,
        mileage: 90000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'Flash Red',
        intColor: 'Black',
        ownership: '2nd Owner',
        rtoLocation: 'RJ-14 (Jaipur)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: false },
        description: 'Timeless design and engaging driving dynamics.',
        images: [{ url: 'https://images.unsplash.com/photo-1616422285623-14ffea3166d4?w=1200&q=80', public_id: 'autovault-cars/polo-2011' }]
    },
    {
        make: 'Honda',
        model: 'Amaze',
        variant: 'VX',
        year: 2018,
        price: 680000,
        mileage: 32000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        bodyType: 'Sedan',
        extColor: 'Radiant Red',
        intColor: 'Beige & Black',
        ownership: '1st Owner',
        rtoLocation: 'GJ-01 (Ahmedabad)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Smooth CVT automatic transmission, ideal for city traffic.',
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80', public_id: 'autovault-cars/amaze-2018' }]
    },
    {
        make: 'Toyota',
        model: 'Innova',
        variant: '2.5 V',
        year: 2015,
        price: 1050000,
        mileage: 145000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 7,
        bodyType: 'SUV',
        extColor: 'Silver Metallic',
        intColor: 'Beige',
        ownership: '1st Owner',
        rtoLocation: 'MH-01 (Mumbai)',
        isFeatured: true,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Highly reliable and spacious. Engine works like a charm despite the miles.',
        images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80', public_id: 'autovault-cars/innova-2015' }]
    },
    {
        make: 'Kia',
        model: 'Seltos',
        variant: 'HTX',
        year: 2019,
        price: 1350000,
        mileage: 41000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Intense Red',
        intColor: 'Black & Beige',
        ownership: '1st Owner',
        rtoLocation: 'KA-03 (Bengaluru)',
        isFeatured: true,
        features: { sunroof: true, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Feature-loaded mid-size SUV. Excellent road presence.',
        images: [{ url: 'https://images.unsplash.com/photo-1620882775199-73fb6eb6fec2?w=1200&q=80', public_id: 'autovault-cars/seltos-2019' }]
    },
    {
        make: 'Maruti Suzuki',
        model: 'Baleno',
        variant: 'Alpha',
        year: 2017,
        price: 620000,
        mileage: 48000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'Nexa Blue',
        intColor: 'All Black',
        ownership: '1st Owner',
        rtoLocation: 'HR-26 (Gurugram)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Premium hatchback with DRLs and SmartPlay infotainment.',
        images: [{ url: 'https://images.unsplash.com/photo-1616422285623-14ffea3166d4?w=1200&q=80', public_id: 'autovault-cars/baleno-2017' }]
    },
    {
        make: 'Hyundai',
        model: 'Verna',
        variant: '1.6 CRDi SX',
        year: 2014,
        price: 520000,
        mileage: 82000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Sedan',
        extColor: 'Sleek Silver',
        intColor: 'Beige & Black',
        ownership: '2nd Owner',
        rtoLocation: 'UP-32 (Lucknow)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: true },
        description: 'Refined diesel engine with punchy performance and good ride quality.',
        images: [{ url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=80', public_id: 'autovault-cars/verna-2014' }]
    },
    {
        make: 'Tata',
        model: 'Altroz',
        variant: 'XZ',
        year: 2020,
        price: 750000,
        mileage: 25000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'High Street Gold',
        intColor: 'Black & Grey',
        ownership: '1st Owner',
        rtoLocation: 'MH-02 (Mumbai)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Safest hatchback in the segment. Pristine condition.',
        images: [{ url: 'https://images.unsplash.com/photo-1616422285623-14ffea3166d4?w=1200&q=80', public_id: 'autovault-cars/altroz-2020' }]
    },
    {
        make: 'Maruti Suzuki',
        model: 'Alto K10',
        variant: 'VXi',
        year: 2010,
        price: 150000,
        mileage: 110000,
        fuelType: 'Petrol',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'Hatchback',
        extColor: 'Silky Silver',
        intColor: 'Grey',
        ownership: '3rd Owner',
        rtoLocation: 'MP-04 (Bhopal)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: false, touchscreen: false, reverseCamera: false },
        description: 'Perfect budget car for learning or city commutes.',
        images: [{ url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=1200&q=80', public_id: 'autovault-cars/alto-2010' }]
    },
    {
        make: 'Mahindra',
        model: 'Scorpio',
        variant: 'S10',
        year: 2016,
        price: 980000,
        mileage: 85000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 7,
        bodyType: 'SUV',
        extColor: 'Pearl White',
        intColor: 'Grey & Blue',
        ownership: '1st Owner',
        rtoLocation: 'PB-01 (Chandigarh)',
        isFeatured: true,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Rugged SUV for all terrains. Impeccable service history.',
        images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80', public_id: 'autovault-cars/scorpio-2016' }]
    },
    {
        make: 'Toyota',
        model: 'Fortuner',
        variant: '2.8 4x4 MT',
        year: 2018,
        price: 2850000,
        mileage: 65000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 7,
        bodyType: 'SUV',
        extColor: 'Super White',
        intColor: 'Chamois',
        ownership: '1st Owner',
        rtoLocation: 'KA-05 (Bengaluru)',
        isFeatured: true,
        features: { sunroof: false, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Ultimate off-roader and status symbol. Very well kept.',
        images: [{ url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=80', public_id: 'autovault-cars/fortuner-2018' }]
    },
    {
        make: 'Renault',
        model: 'Duster',
        variant: 'RxZ',
        year: 2013,
        price: 450000,
        mileage: 120000,
        fuelType: 'Diesel',
        transmission: 'Manual',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Woodland Brown',
        intColor: 'Black & Beige',
        ownership: '2nd Owner',
        rtoLocation: 'WB-02 (Kolkata)',
        isFeatured: false,
        features: { sunroof: false, alloyWheels: true, touchscreen: false, reverseCamera: false },
        description: 'Legendary ride quality. Perfect for bad roads.',
        images: [{ url: 'https://images.unsplash.com/photo-1520031441872-265e4ff70366?w=1200&q=80', public_id: 'autovault-cars/duster-2013' }]
    },
    {
        make: 'MG',
        model: 'Hector',
        variant: 'Sharp',
        year: 2019,
        price: 1450000,
        mileage: 38000,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        seats: 5,
        bodyType: 'SUV',
        extColor: 'Glaze Red',
        intColor: 'All Black',
        ownership: '1st Owner',
        rtoLocation: 'DL-4C (Delhi)',
        isFeatured: true,
        features: { sunroof: true, alloyWheels: true, touchscreen: true, reverseCamera: true },
        description: 'Internet inside! Panoramic sunroof, large touchscreen, loaded with tech.',
        images: [{ url: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&q=80', public_id: 'autovault-cars/hector-2019' }]
    }
];

async function addCars() {
    try {
        const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/autovault';
        console.log('🔌 Connecting to MongoDB...');
        await mongoose.connect(mongoUri);
        console.log('✅ Connected');

        const created = await Car.insertMany(additionalCars);
        console.log(`🌱 Added ${created.length} new car(s) successfully!`);
        
    } catch (err) {
        console.error('❌ Failed to add cars:', err.message);
    } finally {
        await mongoose.disconnect();
    }
}

addCars();
